# Generated by Django 3.2.11 on 2022-01-14 04:47

import django.contrib.auth.models
from django.db import migrations, models
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('allow_register', models.BooleanField(default=False)),
                ('http_server_on', models.BooleanField(default=False)),
                ('ws_server_on', models.BooleanField(default=False)),
                ('twilio_key', models.CharField(blank=True, max_length=30, null=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=50, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_public_key', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_private_key', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_link_url', models.URLField(blank=True, null=True)),
                ('frontend_url', models.URLField(blank=True, null=True)),
                ('backend_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Setup',
                'verbose_name_plural': 'Project Setup',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
