# Generated by Django 3.2.11 on 2022-01-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_alter_setup_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
    ]
